### ISSUE TITLE
unable to save code

### ISSUE THREAD

**Issue by sebalaini** [anand-patel/oc-wysiwyg-editors#112]
I'm writing a theme from scratch and I'm unable to save any code, I'm writing a simple basic html and all the time I switch from code view to CKEditor I lost all code, what is left is just the text

first screenshot it's the saved with all the code, then you click twice source to hide/show again the code view and it's converted in the second image

I'm using Windows 10 with Xampp

![code](https://user-images.githubusercontent.com/17096352/56661406-95288180-6699-11e9-8e6c-f90c238615a9.PNG)

![editor](https://user-images.githubusercontent.com/17096352/56661456-ac676f00-6699-11e9-8547-80290834813b.PNG)

**Comment by cloudwales** [comment]
Try not to use Wysiwig editors to build templates. They strip html code on save. Best thing to do is disable it for the pages and layouts, but enable it for content
