### ISSUE TITLE
Image upload: Something went wrong, please try again

### ISSUE THREAD

**Issue by chrisvidal** [anand-patel/oc-wysiwyg-editors#118]
When I try to upload an image in the editor, Froala for instance, this error shows up

any idea what could be going wrong?

![5c862aec-20f5-407a-9461-6da25625cfa5](https://user-images.githubusercontent.com/2263496/107308775-33324980-6ac4-11eb-9760-58a58a8d1751.jpeg)

**Comment by RoudyTarabay** [comment]
Did you find a solution ?
Switching to ckeditor or tiny allows it to upload an image which is successfully shown on the frontend. However in the editor the paths are wrong so the images do not display. I suspect this only happens if the root of your project is /something.

**Comment by chrisvidal** [comment]
I didnt, I had to reconfigure my server to move my project folder to a subdomain

**Comment by RoudyTarabay** [comment]
I found the solution. The problem is that we have it in a subdomain. You need to fix the path in config/cms.php storage array

**Comment by chrisvidal** [comment]
I tried to update the cms.php but it didn't work out
