### ISSUE TITLE
Needs to be updated to be compatible with the RC release.

### ISSUE THREAD

**Issue by drtzack** [anand-patel/oc-wysiwyg-editors#16]
Needs to be updated to be compatible with the RC release.

**Comment by vbarinov** [comment]
Yeah, I really want to see this wonderful plugin working :factory:

**Comment by caffme** [comment]
This is what I see after installing the plugin:

On: http://october.local/backend/system/settings

```
Call to undefined method [package]
/home/vagrant/Code/october/public/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php line 226

14	Illuminate\Support\ServiceProvider->__call(…)	http://october.local/plugins/anandpatel/wysiwygeditors/src/Barryvdh/Elfinder/ElfinderServiceProvider.php	21
13	Barryvdh\Elfinder\ElfinderServiceProvider->package(…)	http://october.local/plugins/anandpatel/wysiwygeditors/src/Barryvdh/Elfinder/ElfinderServiceProvider.php	21
12	Barryvdh\Elfinder\ElfinderServiceProvider->boot()
```

**Comment by ralf100** [comment]
Same problem here. 
   Call to undefined method [package]

**Comment by Garethderioth** [comment]
@ralf100 Thank you! However, when I try to find files in the TinyMCE there is another error, did you fix it too?

**Comment by anand-patel** [comment]
Sorry for the late reply and update, have fixed issues related to RC release and change upload directory path for flora editor. 

thanks to @ralf100 for the fix. 

@Garethderioth Still Elfinder fix is remaining, will try to fix it soon, need to update Elfinder that is compatible with Laravel 5.

**Comment by Garethderioth** [comment]
@anand-patel Got it. I tried to fix the ElFinder issue but I still don't understand very well the logic.

**Comment by gergo85** [comment]
@anand-patel Thank you for update!

**Comment by anand-patel** [comment]
i hope its working perfectly.

@gergo85  now indikator-filemanager works perfectly :)
