### ISSUE TITLE
Public folder not present

### ISSUE THREAD

**Issue by alesvaupotic** [anand-patel/oc-wysiwyg-editors#19]
Hi,

I've installed the latest version in my clean October CMS installation and it asks for some JS and CSS files from public folder. There is none, however.

![screen shot 2015-03-17 at 09 39 33](https://cloud.githubusercontent.com/assets/1660347/6683686/9f2931c4-cc89-11e4-881a-583ea92e6c63.png)

![screen shot 2015-03-17 at 09 37 51](https://cloud.githubusercontent.com/assets/1660347/6683696/a96cea7c-cc89-11e4-8f84-acd83cee354b.png)

Any clues?

**Comment by anand-patel** [comment]
hmm i need to clenup the code, i was in hurry to fix elfinder so this part was remaining, thanks for pointing out, this will be fixed in next update.

**Comment by anand-patel** [comment]
i am not getting this errors in console, are you sure you are using WysiwygEditors standalone ? or using it with file manager plugin?
