### ISSUE TITLE
Upload of images/files fails

### ISSUE THREAD

**Issue by CptMeatball** [anand-patel/oc-wysiwyg-editors#23]
Whenever I want to upload an image elFinder fails to upload. It can not find the correct folder to upload the files too.

I've tried to add the "uploads/public" folder to the directory but that does;t work.

Error in ElFidner2.0:

"Invalid Backend Configuration.
Readable Volumes not available"

Update: 
Had to manually add the ```uploads``` folder to ```storage/app```

**Comment by anand-patel** [comment]
now is that working ?

**Comment by CptMeatball** [comment]
Yeah! So add that in future updates and all is well!

On a sidenote: CKEditor is the only WYSIWYG that seems to properly align images in ```p```. But's that's not something you can help.
