### ISSUE TITLE
My Settings does not show up on latest version of October CMS

### ISSUE THREAD

**Issue by geocine** [anand-patel/oc-wysiwyg-editors#25]
I have update my October CMS to April 13 `cf1988e` . My Settings is not visible on the left sidebar

![](http://i.imgur.com/KePC7li.png)

**Comment by geocine** [comment]
Ok old instructions, please update the documentation to let us know that it is already located here `Wysiwyg Editors`: 

![](http://i.imgur.com/bm2UX8z.png)

**Comment by anand-patel** [comment]
Now settings for editor is back in sidebar in CMS settings.
