### ISSUE TITLE
Conflict with Media Manager

### ISSUE THREAD

**Issue by michballard** [anand-patel/oc-wysiwyg-editors#30]
Using this plugin with the latest build (251), most editors (except for "October's Rich Editor") are causing errors when viewing CMS pages in the backend.  This seems to be due to the introduction of Media Manager, which is now built into October CMS by default - the other editors may not have functionality to show the Media Manager links.  

This image below shows what it looks like when a CMS page is initially opened - this example has the CKEditor selected.  When using the October's Rich Editor it shows properly.  

![screen shot 2015-04-29 at 11 17 21](https://cloud.githubusercontent.com/assets/8350174/7388940/6c982e14-ee61-11e4-8733-b798caa73436.png)

**Comment by kyestork** [comment]
+1 Having the same issue. Build 252.

**Comment by ar7n** [comment]
+1

**Comment by jbrown8181** [comment]
+1

I will try to have a look this in more detail later in the week.

**Comment by taviroquai** [comment]
Hi,

I did some investigation on this and found 2 problems:

1. Ajax response (json) returns a key (X_OCTOBER_ASSETS) but only with assets from component. The component is using addJs which uses Trait AssetMaker. This addJs moves the asset to the controller assets, but these are not return.

2. Even hacking it using $this->assets['js'][] = ['path' => $jsPath], makes the asset to be returned on X_OCTOBER_ASSETS, but even so, the asset is not loaded BEFORE the call to, ie., tinymce.

I'm a noob on OC so could not see further...
