### ISSUE TITLE
Plugin dont displays the settings in tab SYSTEM

### ISSUE THREAD

**Issue by exotickg1** [anand-patel/oc-wysiwyg-editors#38]
![pshhhh](http://i.gyazo.com/e4fea58d665146419392ab080b817334.png)

**Comment by sarahetter** [comment]
Same issue here.

**Comment by PenguinOfWar** [comment]
The plugin now displays in the user account dropdown of the system area.
![screen shot 2015-07-11 at 15 43 44](https://cloud.githubusercontent.com/assets/1913241/8634125/bd4a4df4-27e3-11e5-812c-6d5fd1f17364.png)

**Comment by noobiemania** [comment]
#43

**Comment by anand-patel** [comment]
Now Editor setting is back to side menu, in CMS section.
