### ISSUE TITLE
plugin doesn't work in RainLab Blog

### ISSUE THREAD

**Issue by Razv1983** [anand-patel/oc-wysiwyg-editors#48]
hi, work in all others, but not in RainLab Blog.

**Comment by hyourinseta** [comment]
same with me. pls anyone?

**Comment by fuzzybaird** [comment]
Yah I am with you guys. Does not work for RainLab Blog.

**Comment by vojtasvoboda** [comment]
:up:

**Comment by vojtasvoboda** [comment]
Fixed in #51

**Comment by vojtasvoboda** [comment]
Fixed and merged. You can close this
