### ISSUE TITLE
Class 'Barryvdh\Elfinder\ElfinderServiceProvider' not found

### ISSUE THREAD

**Issue by Insanityandme** [anand-patel/oc-wysiwyg-editors#55]
Got a fatal error when installing your plugin, works fine without, and I can still navigate around the Updates directory strangely enough, assuming nothing is missing or wrong there but going away from that I get this error:

![screen shot 2016-01-10 at 15 00 34](https://cloud.githubusercontent.com/assets/1380257/12221854/11f86cda-b7ab-11e5-99ec-65aff72f4aa6.png)

**Comment by anand-patel** [comment]
Ok i will find fix for that, reason behind this is at time of installing plugin package is missing in vendor directory, what you can do is goto the root directory of plugin anandpatel/WysiwygEditors and fire composer install command, this will fix issue for now

**Comment by Insanityandme** [comment]
Thanks!

**Comment by larsroettig** [comment]
i have the same issue

**Comment by richlove1** [comment]
Same problem, tried composer install from that directory but hasn't fixed the issue (it did create a vendor directory within the plugin directory and install things there but still getting the error)

**Comment by noobiemania** [comment]
Temporary solution works but unable to find the option to uninstall the plugin.

**Comment by vojtasvoboda** [comment]
Same issue here. Fast fix: go to plugin folder and type `composer install`

**Comment by richlove1** [comment]
I've managed to run the composer install to get past the error but I'm having a number of issues with all editors, none of which are usable:

TinyMCE - Doesn't save content
CKEditor - The editor doesn't load on the page (number of JS files missing, see screenshot)
October's Rich Editor - Strips div tags (can't find setting to change this)
Froala
doesn't utilise media (images etc) already uploaded to the file system when inserting an image
not consistently saving changes made to html source in the WYSIWYG editor

**Comment by anand-patel** [comment]
Sorry for late, please update plugin, i have removed dependency of elfinder, and added octobercms's media manager for uploading images.

Please verify.

Thanks
