### ISSUE TITLE
Class 'Barryvdh\Elfinder\ElfinderServiceProvider' not found

### ISSUE THREAD

**Issue by gothic-prince** [anand-patel/oc-wysiwyg-editors#59]
After activation this plugin, CMS throw exception "Class 'Barryvdh\Elfinder\ElfinderServiceProvider' not found"
How can i to fix?

**Comment by anand-patel** [comment]
Go to the root directory of plugin and fire " composer install" command.

**Comment by gothic-prince** [comment]
$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

I have still the exception.

**Comment by ihilt** [comment]
Running `composer install` in the `plugins/anandpatel/wysiwygeditors` directory worked for me.

**Comment by FrancisVarga** [comment]
@ihilt thanks that helped a lot :)

**Comment by bdimir** [comment]
I am not able to execute commands on my ftp server. Is there any other way around?

**Comment by tresbach** [comment]
You can install the dependencies locally and then upload the `vendor/` folder to your server. Try running:

```
composer require barryvdh/elfinder-builds
composer require barryvdh/elfinder-flysystem-driver
composer require barryvdh/laravel-elfinder
```

**Comment by richlove1** [comment]
Why is there only a workaround posted? Installing this plugin as is still breaks stuff in the back end. Is it going to be resolved in the plugin?

**Comment by abass** [comment]
Agree w/ @richlove1 completely. It's a bit ridiculous - definitely not the most professional way to go about "fixing" it.

**Comment by anand-patel** [comment]
Sorry for late, please update plugin, i have removed dependency of elfinder, and added octobercms's media manager for uploading images. 

Please verify. 

Thanks
