### ISSUE TITLE
Does Rich editor supports bootstrap classes?

### ISSUE THREAD

**Issue by nikita-yugtia** [anand-patel/oc-wysiwyg-editors#76]
hi, I am newbie to the october cms i just want to know that 
how does rich editor supports bootstrap classes?

**Comment by anand-patel** [comment]
You means when you write in editor and it will apply bootstrap classes in editor?

**Comment by nikita-yugtia** [comment]
yes

**Comment by anand-patel** [comment]
Sorry but it does not support this functionality, you need to change it manually.

**Comment by nikita-yugtia** [comment]
ok you mean to add classes manually in css right?

**Comment by nikita-yugtia** [comment]
and do you know this issue I have used rain lab to translate my site into norway everything seems working fine but the language selector options in ckeditor are not visible, richeditor and textarea does shows the options but ckeditor does not.
![image](https://cloud.githubusercontent.com/assets/18721036/15007633/5d0385aa-118f-11e6-90d7-029a8c7e39a6.png)


![image](https://cloud.githubusercontent.com/assets/18721036/15007639/6616488a-118f-11e6-8232-eb45add8465e.png)


Any suggestions?

**Comment by anand-patel** [comment]
Yes i know this issue this plugin in not comfortable with translate plugin. 
i will try to add it, as i get free.
