### ISSUE TITLE
Updates from version 1.2.5 onwards not published on plugin marketplace

### ISSUE THREAD

**Issue by gabrieleciech** [anand-patel/oc-wysiwyg-editors#93]
As stated in the title it seems that the last updates are not present on the marketplace starting from version 1.2.5 as can be shown from [this page](https://octobercms.com/plugin/anandpatel-wysiwygeditors). Is it possible to have them published?

**Comment by gergo85** [comment]
The plugin has updated on the marketplace too.

**Comment by anand-patel** [comment]
As @gergo85 said its on Market Place. sorry for late.
